name: Di Hola

on:
  push:
    branches:
      - main

jobs:
  hola_mundo:
    runs-on: ubuntu-18.04
    steps:
      - name: Imprimir mensaje
        run: |
          echo "Mi primer hola mundo CI / CD"

      - name: Dime la fecha
        run: date
      - run: ls -l
